### ISSUE TITLE
How to use mahimahi as a root user

### ISSUE THREAD

**Issue by lixiaoming0017** [ravinet/mahimahi#112]
When I use the mahimahi as a root user,
 the system say:Died on std::runtime_error: mm-delay: please run as non-root, 
but my experiment is under the enviroment of root,how can i solve the problem.Thank you !!

**Comment by keithw** [comment]
Hello,

The mahimahi shells run setuid root (to create a new network namespace) and then try to drop privileges (back to the user). Because the software is distributed for broad use (e.g. in Debian and Ubuntu), we have conservative safety checks to try to reduce the risk that a setuid program will lead to a security hole. One of them is that the programs *must* be able to drop privileges back to a non-root users.

On your own system, you are certainly welcome to remove those safety checks from the source code and proceed at your own risk if you like.

Look here: https://github.com/ravinet/mahimahi/blob/master/src/util/util.cc#L67

and here: https://github.com/ravinet/mahimahi/blob/master/src/util/system_runner.cc#L23

Best regards,
Keith

**Comment by lixiaoming0017** [comment]
Thank you very much!! I will try again.






At 2017-09-12 03:22:10, "Keith Winstein" <notifications@github.com> wrote:


Hello,

The mahimahi shells run setuid root (to create a new network namespace) and then try to drop privileges (back to the user). Because the software is distributed for broad use (e.g. in Debian and Ubuntu), we have conservative safety checks to try to reduce the risk that a setuid program will lead to a security hole. One of them is that the programs must be able to drop privileges back to a non-root users.

On your own system, you are certainly welcome to remove those safety checks from the source code and proceed at your own risk if you like.

Look here: https://github.com/ravinet/mahimahi/blob/master/src/util/util.cc#L67

and here: https://github.com/ravinet/mahimahi/blob/master/src/util/system_runner.cc#L23

Best regards,
Keith
