### ISSUE TITLE
How to use the command about $MAHIMAHI_BASE

### ISSUE THREAD

**Issue by lixiaoming0017** [ravinet/mahimahi#114]
Thank you very much,but how can i use the $MAHIMAHI_BASE environment variable to refer to the local interface of the "main" container on my computer, outside the mahimahi container.Can i get more information about how to use the mahimahi? There is just one example: mm-delay 50 mm-loss uplink 0.2 sh -c 'ping -c 10 -n $MAHIMAHI_BASE' , i don't know anything about the command.

**Comment by keithw** [comment]
You might consider asking a local Linux user (or any friend familiar with Linux) to look at this with you. The mahimahi shells set the MAHIMAHI_BASE environment variable to the IP address of the "main" container on the system.

You can run:
`$  echo $MAHIMAHI_BASE`
to see what this IP address is. And you can use that in a Web browser or wherever you like. It will often be something like `100.64.0.1`.

**Comment by lixiaoming0017** [comment]
Thank you ,when I use mm-delay later, in the browser to view 100.64.0.1 see the apache server interface,but my scene is written in python with a local httpserver, used to monitor some information from client, you need to run "python server.py" to start the local httpserver , "Server.py" script inside the "server_address = localhost", when I changed the "server_address=100.64.0.1" after the operation "mm-delay 40 python server.py" later suggested that "can not assign the requested address", how to solve this problem.

**Comment by keithw** [comment]
Here are some options that might help. Please do try to work these out with your local experts or anybody else who knows Python if you have trouble.

Option 1: The server needs to listen on "any" IP address. It's possible that using "0.0.0.0" as the server_address will do this. Otherwise, please consult the documentation or ask a Python expert how to make the httpserver listen on the "INADDR_ANY" address.

Option 2: First start mm-delay in one terminal window. Then, in a different terminal window that is still in the main container, start the Python server and have it listen on the MAHIMAHI_BASE address.
