### ISSUE TITLE
Mahimahi and Docker containers

### ISSUE THREAD

**Issue by werber** [ravinet/mahimahi#116]
The reason why I'm asking is that I having an issue running Mahimahi inside docker container. Yes, I know that Mahimahi is not working in docker container (watched a video on site) but I just want to ask if there is a way you have found to make it working there. Or maybe you work on this feature and it will be released in near future? I went over issues here at project and didn't find any topics related to docker.

**Comment by keithw** [comment]
Hello, what error message are you getting? I understand Docker (by default) prevents programs from opening further containers (network namespaces) inside Docker, but I believe you can configure Docker to allow this.

**Comment by soulgalore** [comment]
@werber I haven't tried with Mahimahi (I want to) but I've done some [other networking stuff](https://github.com/sitespeedio/throttle) with Docker. As long as you give the container the right privileges (`--cap-add=NET_ADMIN`) most will work. For some cases I need to be on the same OS host, so you can run your Ubuntu Docker container on Ubuntu (since you give privileges to the underlaying host). Let me know if you get it to work.

**Comment by werber** [comment]
@keithw @soulgalore Thanks a lot! --cap-add=NET_ADMIN --privileged helped to run Mahimahi inside Docker container.

**Comment by soulgalore** [comment]
@werber do you have an example Docker file and your setup? Wanna test and always great to have an working example :)
