### ISSUE TITLE
dnsmasq causes mahimahi commands to hang

### ISSUE THREAD

**Issue by tchainzzz** [ravinet/mahimahi#143]
**OS:** Ubuntu 16.04.2 LTS
**Command:** `mm-loss uplink 0.01`

**Description:** The command hangs for ~10-15 minutes, and then exits with the error message `Died on std::runtime_error: dnsmasq: did not start after 20 attempts`.

**Expected behavior:** The command should spawn a shell with the appropriate parameters. This works on an AWS instance with Ubuntu 16.04, but not on my current machine. 

**What we've tried:**
We observed that mahimahi (i.e. `mm-loss uplink 0.01`) spawns a child process of the following form: `/usr/sbin/dnsmasq --keep-in-foreground --no-resolv --no-hosts -C /dev/null -S 100.64.0.4#48452` -- and this is what causes the hang. We have confirmed that `dnsmasq` is installed on the machine. Running `/usr/sbin/dnsmasq --keep-in-foreground --no-resolv --no-hosts -C /dev/null` yields error message `dnsmasq: failed to create listening socket for port 53: Permission denied`. This error message appears even on the machine where I was able to get mahimahi working. 

**Other details:**

*Installation procedure*
```
$ sudo add-apt-repository ppa:keithw/mahimahi
$ sudo apt-get update
$ sudo apt-get install mahimahi
```

*Contents of `/etc/network/interfaces`*
```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback
```

It appears to me like some configuration issue on this machine prevents `dnsmasq` from starting. I'm happy to provide any other output/details that would be helpful.

**Comment by sadjad** [comment]
By looking at `/var/log/syslog`, it seems that `dnsmasq` starts successfully, but somehow `mm-whatever` process can't reach it (and it's not reachable from outside of the container).

**Comment by keithw** [comment]
@sadjad and I did some debugging this evening. It's a little hard to fully debug without root (mm-delay/mm-loss are suid root to start the container, which makes them untracable by mortals), but I think the problem here is the way this machine is configured with what looks like a firewall that blocks Internet access from within the mahimahi container, and also an /etc/nsswitch.conf / nscd configuration that seems to be waiting on an LDAP or nscd timeout before it can look up the name of a service (in this case, "domain"). I'm about 92% sure that this is the line that's hanging in mahimahi: https://github.com/ravinet/mahimahi/blob/master/src/util/dns_server.cc#L29

We did eventually get an mm-delay shell opened successfully several times -- it just took waiting a looong time! And the container could only access the host but not the Internet, which makes us suspect a firewall configuration (but hard to diagnose for sure without root).

I think your best options here are probably to speak with your sysadmin about changing the firewall or LDAP configuration on this computer, or use a pristine Ubuntu machine (e.g. a VM in AWS), or possibly even a VirtualBox VM (maybe even hosted on this same physical host, or on your own computer).

**Comment by tchainzzz** [comment]
Thanks so much! I'll take a look at these options.

**Comment by HaoxianChen** [comment]
I also ran into the same issue.

May I ask what is this dns for? If I only want to do local test, could I just skip this dns service by commenting the loop out from here?
https://github.com/ravinet/mahimahi/blob/master/src/util/dns_server.cc#L29

Thanks!

**Comment by intothesea** [comment]
The issue might be that the condition ++attempts >= 20 in https://github.com/ravinet/mahimahi/blob/master/src/util/dns_server.cc#L29 is set too low, and the ‘dnsmasq’ process needs time to start. By changing it to ++attempts >= 40 and rebuilding from source, the problem can be resolved.
