### ISSUE TITLE
Delays in the `--dowlink-log` file generated by `mm-link` do not include fixed propagation delays?

### ISSUE THREAD

**Issue by rohitdwivedula** [ravinet/mahimahi#168]
I am trying to run a command like this:

```bash
mm-delay 100 mm-link $FILE $FILE --uplink-queue=droptail --uplink-queue-args="packets=100" --downlink-queue=droptail --downlink-queue-args="packets=100" --downlink-log=log.txt
```

Inside this mahimahi shell, I just run `ping $MAHIMAHI_BASE` for a couple of second and then exit. When I go to inspect the downlink log that was generated, it looks something like this:

```
# mahimahi mm-link (Downlink) [wired6] > log.txt
# command line: 'mm-link' 'wired6' 'wired6' '--uplink-queue=droptail' '--uplink-queue-args=packets=100' '--downlink-queue=droptail' '--downlink-queue-args=packets=100' '--downlink-log=log.txt'
# queue: droptail [packets=100]
# init timestamp: 1734687054312
# base timestamp: 141
# mahimahi config: [delay 100 ms] 
142 # 1504
142 + 80
142 + 52
142 + 80
144 # 1504
144 - 80 2
144 - 52 2
144 - 80 2
```

My understanding of this log is:

- at `t=142ms`, three packets of sizes `80`, `52`, `80` arrive.
- at `t=144ms`, all three of these packets depart (after a delay of `2`ms).

How exactly are packets leaving in `2ms` if we are also running a `mm-delay` shell with a fixed delay of `100ms`. Do I just assume that these numbers (2ms) represent only the queuing delay? To get total delay, I assume I need to add `100ms + 2ms`?

**Comment by keithw** [comment]
Good question! The mahimahi packet emulators function independently; i.e., when you run the command:
```
mm-link $FILE $FILE --uplink-queue=droptail --uplink-queue-args="packets=100" --downlink-queue=droptail --downlink-queue-args="packets=100" --downlink-log=log.txt
```

... that's a self-contained invocation of the `mm-link` program, which is writing out those logs.

In this case, `mm-link` is running inside another container invoked by the `mm-delay 100` command, but the two don't know about each other. The `mm-link` logs don't have any visibility into the delays created by `mm-delay`, any more than they would have visibility into delays the packets experience over the actual Internet.

(The same is true if `mm-delay` is run inside `mm-link`, instead of outside.)

**Comment by rohitdwivedula** [comment]
Thank you so much for the clarification! 🙂
